[build]
  base = "client/"
  publish = "build/web/"
  command = """
    # Install Flutter
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter doctor
    flutter pub get
    flutter build web --release --web-renderer html
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
