name: Deploy Canal+ Flutter Web

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        cd client
        flutter pub get
        
    - name: Analyze code
      run: |
        cd client
        flutter analyze
        
    - name: Run tests
      run: |
        cd client
        flutter test
        
    - name: Build web
      run: |
        cd client
        flutter build web --release --web-renderer html
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/build/web
        cname: canal-plus-mobile.github.io
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: ./client/build/web/
