name: Deploy Canal+ Flutter Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        cd client
        flutter pub get
        
    - name: Build web
      run: |
        cd client
        flutter build web --release
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/build/web
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
        commit_message: Deploy Canal+ Mobile App to GitHub Pages
